#!/usr/bin/env ruby
$LOAD_PATH.unshift 'lib'
require 'room'
require 'merger'

TOKENS = {
  -1 => '.',
  0 => ' ',
  1 => 'X'
}

def format(floor)
  w, h = floor[0..1]
  floor[2..-1].each_slice(w) do |row|
    row.each do |cell|
      print TOKENS[cell]
    end
    puts
  end
end

floor = Room.rect(4, 6)
floor = Room.place(:overwrite, floor, Room.rect(4, 4), -3, -5)
floor = Room.place(:overwrite, floor, Room.rect(7, 3), 9, 5)
floor = Room.place(:merge, floor, Room.rect(10, 6), 2, 1)
floor = Room.pad(floor, 1, 2, 3, 4)
format(floor)
format(floor)
